"""The worklist: read books still missing a rating or a review, most recent first.

Pure planning over the local store. The plan CSV it emits is the input to `gr apply`,
and it respects the invariants by construction: `set_rating` rows are left BLANK for
the user to fill (a rating is never invented), a book whose review the user wrote is
never a review target, and `set_shelf` rows only ever name additive taxonomy shelves —
never the exclusive read / to-read / currently-reading status.
"""

from __future__ import annotations

import csv
import html
import io
import sqlite3
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from datetime import date, datetime

from gr_autopilot.export import EXCLUSIVE_SHELVES, review_state

NEEDS_RATING = "rating"
NEEDS_REVIEW = "review"
NEEDS_STALE = "stale"

_DATE_FORMATS = ("%Y/%m/%d", "%Y-%m-%d")

PLAN_HEADER = (
    "# gr write-plan — generated by `gr queue --plan`. Fill in ratings (1-5); blank rows are",
    "# SKIPPED by `gr apply`. Ratings are yours to give — nothing here guesses one.",
    "#   dry run:  uv run gr apply data/write-plan.csv",
    "#   live:     uv run gr login   then   uv run gr apply data/write-plan.csv --no-dry-run",
    "action,book_id,value",
)


@dataclass(frozen=True)
class QueueEntry:
    book_id: int
    title: str
    author: str
    shelf: str
    rating: int | None
    date_read: str | None
    needs: frozenset[str]


def _parse_date(value: str | None) -> date | None:
    for fmt in _DATE_FORMATS:
        try:
            return datetime.strptime(value or "", fmt).date()  # noqa: DTZ007 - date only
        except ValueError:
            continue
    return None


def build_queue(
    conn: sqlite3.Connection, *, stale_days: int = 90, today: date | None = None
) -> list[QueueEntry]:
    """Read books needing a rating or review (date_read desc), then stale currently-reading."""
    today = today or date.today()  # noqa: DTZ011 - local calendar day is what the user sees
    read: list[QueueEntry] = []
    stale: list[QueueEntry] = []
    for row in conn.execute(
        """
        SELECT b.book_id, b.title, b.author, b.exclusive_shelf, b.my_rating, b.date_read,
               b.date_added, r.source, r.is_empty
        FROM books b LEFT JOIN reviews r ON r.book_id = b.book_id
        WHERE b.exclusive_shelf IN ('read', 'currently-reading')
        ORDER BY b.book_id
        """
    ):
        shelf = str(row["exclusive_shelf"])
        rating = int(row["my_rating"] or 0) or None
        needs: set[str] = set()
        if shelf == "read":
            if rating is None:
                needs.add(NEEDS_RATING)
            if review_state(row["source"], row["is_empty"]) is None:
                needs.add(NEEDS_REVIEW)
        else:
            added = _parse_date(row["date_added"])
            if added is not None and (today - added).days > stale_days:
                needs.add(NEEDS_STALE)
        if not needs:
            continue
        entry = QueueEntry(
            book_id=int(row["book_id"]),
            title=str(row["title"] or ""),
            author=str(row["author"] or ""),
            shelf=shelf,
            rating=rating,
            date_read=row["date_read"] or None,
            needs=frozenset(needs),
        )
        (read if shelf == "read" else stale).append(entry)
    # date_read desc; undated reads sink to the bottom of the read tier
    read.sort(key=lambda e: _parse_date(e.date_read) or date.min, reverse=True)
    return read + stale


def _label(e: QueueEntry) -> str:
    return f"{e.title} — {e.author}"


def plan_rows(
    entries: Sequence[QueueEntry], curate_suggestions: Iterable[tuple[int, str]]
) -> list[list[str]]:
    """`write-plan.csv` rows. Ratings BLANK (the user fills them); shelves additive only."""
    by_id = {e.book_id: e for e in entries}
    rows: list[list[str]] = []
    for e in entries:
        if NEEDS_RATING in e.needs:
            rows.append(["set_rating", str(e.book_id), "", _label(e)])
    for book_id, shelf in sorted(set(curate_suggestions)):
        target = by_id.get(book_id)
        if target is None or shelf in EXCLUSIVE_SHELVES:
            continue
        rows.append(["set_shelf", str(book_id), shelf, _label(target)])
    return rows


def render_plan(rows: Sequence[Sequence[str]]) -> tuple[str, dict[int, int]]:
    """CSV text for `gr apply`, plus book_id -> 1-based line number of its first row."""
    buf = io.StringIO()
    buf.write("\n".join(PLAN_HEADER) + "\n")
    writer = csv.writer(buf, lineterminator="\n")
    line_numbers: dict[int, int] = {}
    for i, row in enumerate(rows, start=len(PLAN_HEADER) + 1):
        line_numbers.setdefault(int(row[1]), i)
        writer.writerow(row)
    return buf.getvalue(), line_numbers


def _stars(rating: int | None) -> str:
    return "★" * rating if rating else "unrated"


def render_html(entries: Sequence[QueueEntry], plan_lines: dict[int, int]) -> str:
    """Static page: one row per book, the rating cell pointing at its plan CSV line."""
    rows = []
    for e in entries:
        line = plan_lines.get(e.book_id)
        rating_cell = (
            f'<input type="number" min="1" max="5" placeholder="1-5"> '
            f"<small>write-plan.csv:{line}</small>"
            if line
            else _stars(e.rating)
        )
        rows.append(
            "<tr>"
            f'<td><a href="https://www.goodreads.com/book/show/{e.book_id}">'
            f"{html.escape(e.title)}</a></td>"
            f"<td>{html.escape(e.author)}</td>"
            f"<td>{html.escape(e.shelf)}</td>"
            f"<td>{html.escape(e.date_read or '')}</td>"
            f"<td>{rating_cell}</td>"
            f"<td>{', '.join(sorted(e.needs))}</td>"
            "</tr>"
        )
    return (
        '<!doctype html>\n<html lang="en"><head><meta charset="utf-8">'
        "<title>Goodreads queue</title>"
        "<style>body{font:15px/1.4 system-ui;margin:2rem;max-width:64rem}"
        "table{border-collapse:collapse;width:100%}td,th{padding:.4rem .6rem;"
        "border-bottom:1px solid #ddd;text-align:left}input{width:3.5rem}"
        "small{color:#666}</style></head><body>"
        f"<h1>Goodreads queue</h1><p>{len(entries)} books. Ratings go into "
        "<code>data/write-plan.csv</code> on the line shown, then "
        "<code>gr apply data/write-plan.csv --no-dry-run</code>. Nothing on this page writes.</p>"
        "<table><thead><tr><th>Title</th><th>Author</th><th>Shelf</th><th>Read</th>"
        "<th>Rating</th><th>Needs</th></tr></thead><tbody>"
        + "".join(rows)
        + "</tbody></table></body></html>\n"
    )
